USE [master]
GO

/****** Object:  Database [BytesIQ.SignalR.SQLXEvents]    Script Date: 24/08/2019 23:41:41 ******/
CREATE DATABASE [BytesIQ.SignalR.SQLXEvents]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BytesIQ.SignalR.SQLXEvents', FILENAME = N'C:\r\MSSQL\DATA\BytesIQ.SignalR.SQLXEvents.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BytesIQ.SignalR.SQLXEvents_log', FILENAME = N'C:\r\MSSQL\DATA\BytesIQ.SignalR.SQLXEvents_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BytesIQ.SignalR.SQLXEvents].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET ARITHABORT OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET RECOVERY FULL 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET  MULTI_USER 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BytesIQ.SignalR.SQLXEvents] SET  READ_WRITE 
GO


