CREATE EVENT SESSION [Monitor_XEvents_150x0080] ON SERVER 
ADD EVENT sqlserver.user_event(
    WHERE ([event_id]=(85)))
WITH (MAX_MEMORY=8192 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=1 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=PER_CPU,TRACK_CAUSALITY=ON,STARTUP_STATE=OFF)
GO


